### ISSUE TITLE
Hi！ Thanks for your sharing! Will the data be publicly available?

### ISSUE THREAD

**Issue by DLwbm123** [DeepTag/cardiac_tagging_motion_estimation#1]

**Comment by DeepTag** [comment]
Due to the pravacy requirement of our medical imaging dataset, we currently have no plan to release it.

**Comment by DeepTag** [comment]
Due to the pravacy requirement of our medical imaging dataset, we currently have no plan to release it. However, our method is unsupervised, you do NOT have to do any annotations to train your own model.

**Comment by DeepTag** [comment]
Due to the pravacy requirement of our medical imaging dataset, we currently have no plan to release it. However, our method is unsupervised, you do NOT have to do any annotations to train your own model with our code.

**Comment by DeepTag** [comment]
Due to the pravacy requirement of our medical imaging dataset, we currently have no plan to release it. However, our method is unsupervised, so you do NOT have to do any annotations to train your own model with our code.
