### ISSUE TITLE
Can you please provide one data example and one example of json file?

### ISSUE THREAD

**Issue by MinaJf** [DeepTag/cardiac_tagging_motion_estimation#3]
Hi
Could you please provide one data example and one example of json file?
I know that your data are not publicly available, can you just provide any examples that we can figure out the configuration and input types better

**Comment by DeepTag** [comment]
The original data is a time sequence of images: [ 1, phase, height, width].

Then we pick up (phase - 1) fixed images and switch the batch size and phase so the DL model's input data type is  [ phase-1, 1, height, width]. Also, we pick up (phase - 1) moving images and switch the batch size and phase so the DL model's input data type is  [ phase-1, 1, height, width]. The DL model should have both the fixed image and moving image as the inputs.

The output deformation field data type is [ phase-1, 2, height, width] with 2 channels of the x and y motion components.
