### ISSUE TITLE
predict one test example

### ISSUE THREAD

**Issue by tli3** [DeepTag/cardiac_tagging_motion_estimation#4]
Hello, we are trying to predict a new test example but I am not quite sure about the steps for your codes here. 
For example, given a nifti image 240*256*1*20 (20 time slices), shall we do preprocessing first (normalize_data_2d?) and then using your [test_the_net.py] and [pro_new_model.pth]? If there is an example on this or an information file on this that will be great

**Comment by tli3** [comment]
240*256*1*20

**Comment by tli3** [comment]
sorry a typo here 240x256x1x20

**Comment by DeepTag** [comment]
You should normalize the testing data first.
